# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Build
  jobs:
    - job: Build

      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - task: UseNode@1
        inputs:
          version: 12.x

      - task: Npm@1
        displayName: 'npm ci'
        inputs:
          command: ci
          verbose: false

      - task: Npm@1
        displayName: 'npm build'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run build-deploy'

      - task: Npm@1
        displayName: 'npm ci --production'
        inputs:
          command: custom
          verbose: false
          customCommand: 'ci --production'

      - script: |
          cd $(System.DefaultWorkingDirectory)
          pwd
          rm -rfv src .vscode .e* .n* copystaticassets.ts tsconfig* 
        displayName: 'Delete Files...'

      - task: ArchiveFiles@1
        displayName: 'Archive files '
        inputs:
          rootFolder: '$(System.DefaultWorkingDirectory)'
          includeRootFolder: false
          archiveType: 'default'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true

      - task: CopyFiles@2
        displayName: 'Copy File to: $(TargetFolder)'
        inputs:
          SourceFolder: '$(Build.ArtifactStagingDirectory)'
          Contents: '$(Build.BuildId).zip'
          TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'
          CleanTargetFolder: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: littlefoot-web'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'
          ArtifactName: 'littlefoot-web'
          publishLocation: 'Container'


